# Generated by Django 4.0.4 on 2022-05-12 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookinfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinfo',
            name='image',
        ),
    ]
