# Generated by Django 4.0.4 on 2022-05-24 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookinfo', '0004_alter_bookinfo_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='synopsis',
            field=models.TextField(max_length=501),
        ),
    ]
