# Generated by Django 4.0.4 on 2022-05-28 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookinfo', '0005_alter_bookinfo_synopsis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='synopsis',
            field=models.TextField(max_length=501, null=True),
        ),
    ]
