# Generated by Django 4.0.4 on 2022-05-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookinfo', '0006_alter_bookinfo_synopsis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookimage',
            name='image',
            field=models.ImageField(null=True, upload_to='book_images'),
        ),
    ]
