# Generated by Django 4.0.4 on 2022-05-11 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='USERNAME_FIELD',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='USERNAME_FIELD',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
    ]
