# Generated by Django 4.0.4 on 2022-05-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_username_field_admin_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='borrow_num',
            field=models.IntegerField(default=0),
        ),
    ]
