# Generated by Django 4.0.4 on 2022-06-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_student_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='number',
        ),
        migrations.AddField(
            model_name='admin',
            name='name',
            field=models.CharField(default='no_name', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='no_name', max_length=100),
        ),
    ]
