# Generated by Django 4.0.4 on 2022-06-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_admin_number_remove_student_number_admin_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
