# Generated by Django 4.0.4 on 2022-06-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_admin_name_alter_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='question',
            field=models.CharField(choices=[('父亲的名字是什么？', '父亲的名字是什么？'), ('母亲的名字是什么？', '母亲的名字是什么？'), ('宠物的名字是什么？', '宠物的名字是什么？'), ('你最喜欢的颜色是什么？', '你最喜欢的颜色是什么？'), ('你最喜欢的食物是什么？', '你最喜欢的食物是什么？'), ('你最喜欢的作家是谁？', '你最喜欢的作家是谁？'), ('你最喜欢书的书名是什么？', '你最喜欢书的书名是什么？'), ('你的专业是什么？', '你的专业是什么？')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='question',
            field=models.CharField(choices=[('父亲的名字是什么？', '父亲的名字是什么？'), ('母亲的名字是什么？', '母亲的名字是什么？'), ('宠物的名字是什么？', '宠物的名字是什么？'), ('你最喜欢的颜色是什么？', '你最喜欢的颜色是什么？'), ('你最喜欢的食物是什么？', '你最喜欢的食物是什么？'), ('你最喜欢的作家是谁？', '你最喜欢的作家是谁？'), ('你最喜欢书的书名是什么？', '你最喜欢书的书名是什么？'), ('你的专业是什么？', '你的专业是什么？')], max_length=50, null=True),
        ),
    ]
