# Generated by Django 4.0.4 on 2022-06-23 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_admin_answer_student_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='question',
        ),
        migrations.RemoveField(
            model_name='student',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='student',
            name='question',
        ),
    ]
