# Generated by Django 4.0.4 on 2022-05-22 05:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_student_borrow_num'),
        ('bookinfo', '0004_alter_bookinfo_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('已借书', '已借书'), ('已还书', '已还书'), ('已逾期', '已逾期'), ('逾期已付款', '逾期已付款')], default='已借书', max_length=100)),
                ('borrow_date', models.DateTimeField(default=datetime.datetime(2022, 5, 22, 13, 44, 28, 104456))),
                ('return_date', models.DateTimeField(default=datetime.datetime(2022, 8, 20, 13, 44, 28, 104456))),
                ('returned_date', models.DateTimeField(null=True)),
                ('bookinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookinfo.bookinfo')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student')),
            ],
        ),
    ]
