# Generated by Django 4.0.4 on 2022-05-12 11:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('return_dailynum', models.IntegerField(validators=[django.core.validators.MinLengthValidator(0)])),
                ('borrow_dailynum', models.IntegerField(validators=[django.core.validators.MinLengthValidator(0)])),
                ('refund_amount', models.IntegerField(validators=[django.core.validators.MinLengthValidator(0)])),
            ],
            options={
                'verbose_name': 'Book',
            },
        ),
    ]
