# Generated by Django 4.0.4 on 2022-05-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailydata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datainfo',
            options={'verbose_name': 'DailyData'},
        ),
        migrations.AlterField(
            model_name='datainfo',
            name='borrow_dailynum',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='datainfo',
            name='refund_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='datainfo',
            name='return_dailynum',
            field=models.IntegerField(),
        ),
    ]
